[project]
authors = ["Martin Fleischmann <martin@martinfleischmann.net>"]
channels = ["conda-forge"]
description = "A course on spatial data science in Python"
name = "sds"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "24.10"

[tasks]

[dependencies]
python = "3.12.*"
astropy = ">=6"
contextily = ">=1.6"
datashader = ">=0.16"
esda = ">=2.6"
geocube = ">=0.5"
geopandas = ">=1.0"
geopy = ">=2.4"
h3-py = ">=3.7"
httpx = ">=0.27"
libpysal = ">=4.12.0"
mgwr = ">=2.2"
openpyxl = ">=3.1"
osmnx = ">=1.9"
pandas = ">=2.2"
pointpats = ">=2.4"
pyarrow = ">=17"
pyinterpolate = ">=0.5"
pyogrio = ">=0.9"
rioxarray = ">=0.17"
rasterio = ">=1.3"
scikit-learn = "*"
seaborn = ">=0.13"
spglm = ">=1.1"
spreg = ">=1.4"
statsmodels = ">=0.14"
tobler = ">=0.11.3"
xarray = ">=2024.7"
xvec = ">=0.3"
dask-expr = ">=1"
ipykernel = "*"
jupyter-cache = "*"
jupyterlab = "*"
pip = "*"

[pypi-dependencies]
kdepy = "*"
